Fix: wrong denom check at RegsterCoin and remove IBC-related tests
b-harvest/basechain-archived pull request #6
Opened 2024-07-29 06:25 UTC by jasonsong0

## Description

- This is based on the [PR](https://github.com/b-harvest/Canto/pull/78) patched in canto v8. 

### Problem

- `coinMetadata.Base` is used as the denom for the token pair
- but `coinMetadata.Name` was used for checking registered token pair

### Solution
- Check registered token pair using `coinMatadata.Base`

### Proof of Work

- [TestCase](https://github.com/jasonsong0/basechain/blob/ba501785e43322e41e3d5cfa39951908d93bff19/x/erc20/keeper/proposals_test.go#L221C1-L242C5): The test case for duplicate denom registering passes with the fix in the PR 

### Testcode Refactoring
- IBC-realted tests are removed because IBC features have been removed in Basechain.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] targeted the correct branch (see [PR Targeting](https://github.com/canto-network/canto/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] provided a link to the relevant issue or specification
- [x] included the necessary unit and integration tests
- [ ] reviewed "Files changed" and left comments if necessary
 
### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2024-07-29 07:59 UTC, zsystm approved these changes
LGTM

2024-07-29 08:17 UTC, dongsam requested changes
Need to Cherry-pick below PRs without canto v8(sdk 50) dependent code
- [ ]  https://github.com/b-harvest/Canto/pull/68
- [x]  https://github.com/b-harvest/Canto/pull/78

Could you backport patch for https://github.com/b-harvest/Canto/pull/68   or If you think a is not necessary, please leave a comment about the reason @jasonsong0

2024-07-29 09:14 UTC, jasonsong0 commented
> Need to Cherry-pick below PRs without canto v8(sdk 50) dependent code
> 
> * [ ]   [feat(erc20): add indexes at genesis state to track active token pairs Canto#68](https://github.com/b-harvest/Canto/pull/68)
> * [x]   [Fix: wrong denom check at RegisterCoin Canto#78](https://github.com/b-harvest/Canto/pull/78)
> 
> Could you backport patch for [b-harvest#68](https://github.com/b-harvest/Canto/pull/68) and Review request again? @jasonsong0

The index was added as a patch for the existence of multiple token pairs with the same denom, which should not happen if the above PR is fixed.
The name change better serves its purpose, so I'll apply the commit.

2024-07-29 09:37 UTC, dongsam commented
@jasonsong0 It might be a good to backporting patch proceed with https://github.com/b-harvest/Canto/pull/68 even after applying the duplication prevention patch https://github.com/b-harvest/Canto/pull/78 for the following reasons:
- The genesis export/import logic has been clearly modified.
- The DenomMap(`TokenPairDenomIndex`) and ERC20Map(`TokenPairERC20AddressIndex`), which were missing in the genesis state, have been explicitly added.
- By using common code and naming through backporting, there are benefits in terms of future maintenance.

@zsystm , If you have any opinions on this as well, Please let us know

2024-07-30 00:49 UTC, zsystm commented
> @jasonsong0 It might be a good to backporting patch proceed with [b-harvest#68](https://github.com/b-harvest/Canto/pull/68) even after applying the duplication prevention patch [b-harvest#78](https://github.com/b-harvest/Canto/pull/78) for the following reasons:
> 
> * The genesis export/import logic has been clearly modified.
> * The DenomMap(`TokenPairDenomIndex`) and ERC20Map(`TokenPairERC20AddressIndex`), which were missing in the genesis state, have been explicitly added.
> * By using common code and naming through backporting, there are benefits in terms of future maintenance.
> 
> @zsystm , If you have any opinions on this as well, Please let us know

Agree with @dongsam 
@jasonsong0 I think it's good to have https://github.com/b-harvest/Canto/pull/68

2024-07-30 01:33 UTC, zsystm reviewed
@jasonsong0 

- same denom and multiple token pair bug should not happen in this codebase.
- the previous comments could be interpreted as if this issue can already occur or has occurred, so I have revised the comment

2024-07-30 01:33 UTC, zsystm commented on x/erc20/genesis.go
> +	// but only one which is in indexes are valid.
@jasonsong0 
```suggestion
	// multiple token pairs should not be registered with the same denom, 
	// but if this happens, only the one in the index is valid.
```

2024-07-30 01:33 UTC, zsystm commented on x/erc20/genesis_test.go
> +	// uqstars1 is deployed first.
@jasonsong0 
```suggestion
        // The following test codes are to prove that multiple token pairs should not be registered 
        // with the same denom, but if this happens, only the one in the index is valid.
	// uqstars1 and uqstars2 have same denom
	// uqstars1 is deployed first.
```

2024-07-30 02:00 UTC, zsystm approved these changes
LGTM
FYI. @jasonsong0 test-coverage CI failed.

2024-07-30 02:02 UTC, dongsam commented on x/erc20/genesis_test.go
> +		ChainID:         "test-chainid",
The chainID of Ethermint chains should be EIP155 Ethereum-compatible [Ref](https://github.com/Canto-Network/ethermint/blob/db8920e278dbf6ed03aa63212f8bdd3f83b6e68d/types/chain_id.go#L1-L50)

if you keep `canto_9000-1`,  we can refactor at a time

2024-07-30 02:05 UTC, dongsam commented on x/erc20/genesis_test.go
> +		ChainID:         "test-chainid",
Please let me know if it was an intentional correction or if you had any other intentions

2024-07-30 02:51 UTC, dongsam approved these changes

2024-07-30 02:52 UTC, dongsam commented
LGTM, Please merge it If all the work is done @jasonsong0

2024-07-30 02:57 UTC, merged